### ISSUE TITLE
Service not installing on Bullseye

### ISSUE THREAD

**Issue by CommanderCoder** [pimoroni/grow-python#18]
I tried to install grow-python on a new install of Raspbian Bullseye and it doesn't install the service.

install.sh seems to have the relevant code
install-bullseye.sh doesn't

**Comment by helgibbons** [comment]
Just did a fresh install on Bullseye (Lite) using the one line installer and it worked fine, so hopefully this issue is now sorted - do re-open if not!

**Comment by Makeshift** [comment]
This still appears to be an issue on 32bit Bullseye on a Pi Zero W 1.1 (Yes, it's old!)

Specifically at least, trying to run the command `/usr/bin/grow-monitor /etc/default/grow` (with working directory `/usr/share/grow-monitor`) results in permission denied:

```
Traceback (most recent call last):
  File "/usr/bin/grow-monitor", line 1157, in <module>
    main()
  File "/usr/bin/grow-monitor", line 1151, in main
    config.save()
  File "/usr/bin/grow-monitor", line 973, in save
    with open(settings_file, "w") as file:
PermissionError: [Errno 13] Permission denied: '/etc/default/grow'
```

After fixing the permissions issue, the systemd service will still not start and appears to hang indefinitely (both in `./install.sh` and manually starting it)

I'm currently debugging and will edit this post if I find anything interesting.

**Comment by Makeshift** [comment]
I've opened a ticket over at raspberrypi/linux#5029. Any input to see if I've been misdirected by something would be appreciated!
