### ISSUE TITLE
If there is no will (or budget) to take this project forward

### ISSUE THREAD

**Issue by jorjun** [pimoroni/grow-python#25]
Say so. 

Or people's time will be wasted. You can't avoid marketing. Right now Pimoroni is engaging in negative marketing through neglect and omission.

**Comment by Gadgetoid** [comment]
Ahoy. I'm a little confused here, is this in respect to your pull request (#23) or something else?

**Comment by Gadgetoid** [comment]
Oh. I don't disagree, but for the most part we just write and maintain drivers, libraries and examples and leave the rest as an exercise to the user. Don't want to have all the fun ourselves!

I am, however, open to suggestions (of course your PR is implicitly one such suggestion) about what we can do to move it forward, and what forward looks like. In some repositories we've linked user projects to make it clearer that a wider ecosystem exists- maybe we need more of that.

I see also that issues and PRs have been neglected here and a few dozen repositories and that's actually something we're taking action on this month- getting this stuff out of my head and into an accountable internal process and that sort of thing.

P.S. if you have the time to update your PR I think @helgibbons has tested it today.

**Comment by bsimmo** [comment]
I think I have MQTT in mine already but for HA  (HomeAssistant) as I know a lot use HA setup for this sort of thing, mine is poor but works, just.

Maybe adding a few links to know projects based on it, I wouldn't put MQTT in the base driver/setup but as a additional example as I'd likely have to strip it all out for a different style setup.
